#!/usr/bin/env python3
"""simple script to rewrite a VCF file with digest-based identifiers

https://github.com/reece/vcf-digester
"""


import argparse
import gzip
import hashlib
import logging
import random
import sys

import coloredlogs
from pysam import VariantFile


_logger = logging.getLogger()

INFO_FIELD_ID = "ADIG"


def parse_args(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("VCF_IN")
    ap.add_argument("--out", "-o",
                    default="-")
    ap.add_argument(
        "--failure-probability", "-f",
        type=float,
        default=0)
    opts = ap.parse_args(argv)
    return opts


def record_digests(record):
    def digest(d):
        return hashlib.sha512(d.encode("ascii")).hexdigest()[:8]

    spdi_loc = f"{record.chrom}:{record.pos-1}:{len(record.ref)}"
    alts = record.alts if record.alts else []
    # payloads like ['20:14369:1', '20:14369:1:G', '20:14369:1:A']
    alleles = [f"{spdi_loc}:{a}" for a in [record.ref, *alts]]
    digests = ["L" + digest(spdi_loc)] + ["A"+digest(p) for p in alleles]
    return digests


if __name__ == "__main__":
    coloredlogs.install(level="INFO")

    opts = parse_args(sys.argv[1:])

    _logger.warning(f"I will randomly die with probabilty {opts.failure_probability}")

    if random.random() < opts.failure_probability:
        raise Exception("Dear silly human: I randomly died to spite you!")

    vcf_in = VariantFile(filename=opts.VCF_IN)
    vcf_in.header.info.add(INFO_FIELD_ID, "1", "String", "allele digests")

    vcf_out = VariantFile(opts.out, "w", header=vcf_in.header)

    for record in vcf_in:
        ld, *ads = record_digests(record)
        if record.id:
            record.id += ";" + ld
        else:
            record.id = ld
        record.info[INFO_FIELD_ID] = ",".join(ads)
        vcf_out.write(record)
